In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6])
b = np.array([7,8,9,10,11,12])
c=[1,2,3,4,5,6]
d=[7,8,9,10,11,12]

In [4]:
a+b # numpy array does one to one element addition

array([ 8, 10, 12, 14, 16, 18])

In [3]:
c+d # standard array does concatenation

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [5]:
np.add(a,b)

array([ 8, 10, 12, 14, 16, 18])

In [7]:
np.subtract(a,b)

array([-6, -6, -6, -6, -6, -6])

In [8]:
a*b

array([ 7, 16, 27, 40, 55, 72])

In [9]:
np.dot(a,b) # dot product of two vectors

217

In [19]:
np.cross(a[:3],b[3:])

array([-9, 18, -9])

In [31]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
b = np.transpose(a)
b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [34]:
c = b.reshape(2,3)
c

array([[1, 4, 2],
       [5, 3, 6]])

In [40]:
d = np.zeros((5,2))
d

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [42]:
e = np.ones((2,3))
e

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [45]:
m = np.arange(6).reshape(2,3)
m

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
m[:,1]

array([1, 4])

In [51]:
m.nbytes

48